### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#12]
Hello Nik!
I don't want to be a bother to you .... I'm going through the code (iso.rb), trying to figure out how to add this feature, but I don't see how to add this myself.

It would be great on the ISO List screen to show which VM(s) each .ISO is attached.
Or, on the Server List screen, where 1 or multiple IPs are listed, to have another column showing the .ISO attached to the VM.

Thank you for any effort or assistance!
-dave

**Comment by niwo** [comment]
Hello Dave

I added a filter option to the vm#list command which can filter the Objects returned by the API on any key they contain.
You can use it like this in order to show only vms which have a certain ISO attached:

```
cloudstack-cli vm list --filter isoname:debian-7.4.0-amd64-netinst
```

Please note that you can print list output also in YAML or JSON to see all attributes the Objects contain (and which you can filter):

```
cloudstack-cli vm list --format yaml
```

**Comment by niwo** [comment]
The --filter option should work fine with v1.4.1.

Cheers,
Nik

**Comment by sdrose** [comment]
Thank you, Nik!
I can’t wait to try this option!!!

-dave
